import { UserRole } from '@prisma/client';

export const ROLE_PERMISSIONS: Record<UserRole, string[]> = {
  [UserRole.CLIENT_USER]: [
    'TICKET_CREATE',
    'TICKET_VIEW_OWN',
    'TICKET_REOPEN',
    'COMMENT_CREATE',
    'ATTACHMENT_UPLOAD',
    'MEMBER_VIEW',
    'KB_VIEW',
    'SLA_VIEW',
    'ROADMAP_VOTE',
  ],
  [UserRole.CLIENT_ADMIN]: [
    'TICKET_CREATE',
    'TICKET_VIEW_ORG',
    'TICKET_EDIT',
    'TICKET_STATUS_CHANGE',
    'TICKET_REOPEN',
    'COMMENT_CREATE',
    'COMMENT_DELETE',
    'ATTACHMENT_UPLOAD',
    'ATTACHMENT_DELETE',
    'MEMBER_INVITE',
    'MEMBER_MANAGE',
    'MEMBER_VIEW',
    'REPORT_VIEW',
    'REPORT_EXPORT',
    'KB_VIEW',
    'SLA_VIEW',
    'WORKSPACE_CONFIGURE',
    'BRANDING_CONFIGURE',
    'ROADMAP_VOTE',
    'ROADMAP_REQUEST',
  ],
  [UserRole.AGENT]: [
    'TICKET_VIEW_ALL',
    'TICKET_EDIT',
    'TICKET_STATUS_CHANGE',
    'COMMENT_CREATE',
    'COMMENT_INTERNAL',
    'ATTACHMENT_UPLOAD',
    'MEMBER_VIEW',
    'KB_VIEW',
    'SLA_VIEW',
    'ESCALATION_VIEW',
    'AI_SUGGEST',
    'AI_FEEDBACK',
  ],
  [UserRole.LEAD]: [
    'TICKET_VIEW_ALL',
    'TICKET_EDIT',
    'TICKET_STATUS_CHANGE',
    'TICKET_ASSIGN',
    'TICKET_DELETE',
    'TICKET_REOPEN',
    'COMMENT_CREATE',
    'COMMENT_DELETE',
    'COMMENT_INTERNAL',
    'ATTACHMENT_UPLOAD',
    'ATTACHMENT_DELETE',
    'MEMBER_INVITE',
    'MEMBER_MANAGE',
    'MEMBER_VIEW',
    'REPORT_VIEW',
    'REPORT_EXPORT',
    'KB_VIEW',
    'SLA_VIEW',
    'SLA_CONFIGURE',
    'ESCALATION_VIEW',
    'ESCALATION_CONFIGURE',
    'ROUTING_VIEW',
    'AI_SUGGEST',
    'AI_FEEDBACK',
    'DELIVERY_VIEW',
    'ONBOARDING_VIEW',
    'ONBOARDING_MANAGE',
    'PROJECT_VIEW',
    'PROJECT_CREATE',
    'PROJECT_EDIT',
    'PROJECT_DELETE',
    'AI_PROJECT_INSIGHTS',
    'AI_PROJECT_REPORTS',
    'AI_PROJECT_QA',
  ],
  [UserRole.ADMIN]: [
    'TICKET_CREATE',
    'TICKET_VIEW_ALL',
    'TICKET_EDIT',
    'TICKET_STATUS_CHANGE',
    'TICKET_ASSIGN',
    'TICKET_DELETE',
    'TICKET_REOPEN',
    'COMMENT_CREATE',
    'COMMENT_DELETE',
    'COMMENT_INTERNAL',
    'ATTACHMENT_UPLOAD',
    'ATTACHMENT_DELETE',
    'MEMBER_INVITE',
    'MEMBER_MANAGE',
    'MEMBER_VIEW',
    'REPORT_VIEW',
    'REPORT_EXPORT',
    'KB_VIEW',
    'KB_MANAGE',
    'SLA_VIEW',
    'SLA_CONFIGURE',
    'ESCALATION_VIEW',
    'ESCALATION_CONFIGURE',
    'ROUTING_VIEW',
    'AI_SUGGEST',
    'AI_FEEDBACK',
    'AUDIT_VIEW',
    'WORKSPACE_CONFIGURE',
    'SYSTEM_CONFIGURE',
    'COMPLIANCE_VIEW',
    'DELIVERY_VIEW',
    'DELIVERY_MANAGE',
    'ONBOARDING_VIEW',
    'ONBOARDING_MANAGE',
    'ROADMAP_VOTE',
    'ROADMAP_REQUEST',
    'PROJECT_VIEW',
    'PROJECT_CREATE',
    'PROJECT_EDIT',
    'PROJECT_DELETE',
    'AI_PROJECT_INSIGHTS',
    'AI_PROJECT_REPORTS',
    'AI_PROJECT_QA',
    'USER_PERMISSION_MANAGE',
    'SKILL_ASSIGN',
    'WORKLOAD_VIEW',
    'SCORING_CONFIGURE',
    'USER_IMPORT',
    'PASSWORD_RESET',
  ],
};

export function getPermissionsForRole(
  role: UserRole,
  overrides: { permission: string; type: 'GRANT' | 'REVOKE' }[] = [],
): string[] {
  const base = new Set(ROLE_PERMISSIONS[role] ?? []);

  for (const override of overrides) {
    if (override.type === 'GRANT') {
      base.add(override.permission);
    } else if (override.type === 'REVOKE') {
      base.delete(override.permission);
    }
  }

  return Array.from(base);
}
